SaferMS/Controllers/AdministrarController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class AdministrarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Administrar()
        {
            return View();
        }
    }
}

SaferMS/Controllers/InicioAdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class InicioAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InicioAdmin()
        {
            return View();
        }
    }


}

SaferMS/Views/InicioAdmin/InicioAdmin.cshtml
@{
    ViewData["Title"] = "Inicio Adminstrador";
}

<div class="text-center">
    <h1 class="display-4">Administrador</h1>

</div>

<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">

        <!--First slide-->
        <div class="carousel-item active">
            <div class="view" style="background-image: url('https://static.retema.es/media/images/noticias/oIk7BGCTDiStoBauy9EhvHMcRf0R9PF5yE.jpg') ;
                     background-repeat: no-repeat; background-size: cover; ">

                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                    <!-- Content -->
                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong></strong>
                        </h1>

                        <p>
                            <strong></strong>
                        </p>

                        <p class="mb-4 d-none d-md-block">
                            <strong></strong>
                        </p>

                        <a target="_blank" href="https://mdbootstrap.com/bootstrap-tutorial/" class="btn btn-outline-white btn-lg">
                            <i class="fa fa-graduation-cap ml-2"></i>
                        </a>
                    </div>

                </div>

            </div>
        </div>

        <div class="carousel-item">
            <div class="view" style="background-image: url('https://www.ulima.edu.pe/sites/default/files/styles/600x300/public/news/img/agenda-tecnologiacemento-may2020.jpg?itok=kswsNTH3');
                    background-repeat: no-repeat; background-size: cover; ">


                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">


                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong></strong>
                        </h1>

                        <p>
                            <strong></strong>
                        </p>

                        <p class="mb-4 d-none d-md-block">
                            <strong></strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/bootstrap-tutorial/" class="btn btn-outline-white btn-lg">
                            <i class="fa fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="carousel-item">
            <div class="view" style="background-image: url('https://revistas.eleconomista.es/binrepository/768x512/0c40/768d432/none/129223038/FRLV/istock-1133989173_61-1776636_20201102152307.jpg');
                                                           background-repeat: no-repeat; background-size: cover; ">

                <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong></strong>
                        </h1>

                        <p>
                            <strong></strong>
                        </p>

                        <p class="mb-4 d-none d-md-block">
                            <strong></strong>
                        </p>
                        <a target="_blank" href="https://mdbootstrap.com/bootstrap-tutorial/" class="btn btn-outline-white btn-lg">
                            <i class="fa fa-graduation-cap ml-2"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>

</div>

<div class="modal-footer">
    <div style="width:100%;text-align:center;">
        <a class="btn btn-primary" asp-area="" asp-controller="Administrar" asp-action="Administrar">Administrar</a>
        <button type="submit" class="btn btn-primary" data-dismiss="modal">Autorizaciones</button>
        <button type="submit" class="btn btn-primary" data-dismiss="modal">Seguimientos</button>
        <button type="submit" class="btn btn-primary" data-dismiss="modal">Mis registros</button>
        <button type="submit" class="btn btn-primary" data-dismiss="modal">Mi perfil</button>
    </div>
</div>