SaferMS/Controllers/InicioAdminController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class InicioAdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InicioAdmin()
        {
            return View();
        }
    }


}

SaferMS/Controllers/InicioDirectivoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class InicioDirectivoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InicioDirectivo()
        {
            return View();
        }
    }


}

SaferMS/Controllers/InicioRespSegController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class InicioRespSegController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InicioRespSeg()
        {
            return View();
        }
    }


}

SaferMS/Controllers/InicioUsuarioSController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SaferMS.Controllers
{
    public class InicioUsuarioSController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InicioUsuarioS()
        {
            return View();
        }
    }


}

SaferMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaferManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Safer Management System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="IniciarSesion">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InicioAdmin" asp-action="InicioAdmin">Administrador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InicioDirectivo" asp-action="InicioDirectivo">Directivo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InicioRespSeg" asp-action="InicioRespSeg">Responsable</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InicioUsuarioS" asp-action="InicioUsuarioS">Usuario simple</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Powered by Software Solutions Company <a asp-area="" asp-controller="" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)




</body>
</html>